version: "2"
run:
  issues-exit-code: 1
  tests: false
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
  path-prefix: ""
linters:
  default: none
  enable:
    - asasalint
    - bodyclose
    - copyloopvar
    - cyclop
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - exhaustive
    - forbidigo
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl
  settings:
    cyclop:
      max-complexity: 20
      package-average: 0
    exhaustive:
      default-signifies-exhaustive: true
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - wrapperFunc
        - importShadow
        - unnamedResult
        - hugeParam
        - commentFormatting
        - paramTypeCombine
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gosec:
      excludes:
        - G404
    govet:
      enable:
        - shadow
    nolintlint:
      require-explanation: false
      require-specific: false
    predeclared:
      ignore:
        - error
    revive:
      rules:
        - name: exported
          disabled: true
    staticcheck:
      checks:
        - all
        - -ST1003
    wsl:
      allow-assign-and-anything: true
      allow-cuddle-declarations: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - cyclop
        path: (.+)_test\.go
    paths:
      - .*mock.*\.go$
      - .*\.pb\.go$
      - third_party$
      - builtin$
      - examples$
issues:
  uniq-by-line: false
  max-same-issues: 0
  #new-from-merge-base: main # ONLY lint new changes that are not in main branch
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - .*mock.*\.go$
      - .*\.pb\.go$
      - third_party$
      - builtin$
      - examples$
