// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: data_object_enricher/data_object_enricher.proto

package data_object_enricher

import (
	config "github.com/raito-io/cli/base/util/config"
	version "github.com/raito-io/cli/base/util/version"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DataObjectEnricherConfig represents the configuration that is passed from the CLI to the DataObjectEnricher plugin interface.
// It contains all the necessary configuration parameters for the plugin to function.
type DataObjectEnricherConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigMap     *config.ConfigMap      `protobuf:"bytes,1,opt,name=config_map,json=configMap,proto3" json:"config_map,omitempty"`
	InputFile     string                 `protobuf:"bytes,2,opt,name=input_file,json=inputFile,proto3" json:"input_file,omitempty"`
	OutputFile    string                 `protobuf:"bytes,3,opt,name=output_file,json=outputFile,proto3" json:"output_file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataObjectEnricherConfig) Reset() {
	*x = DataObjectEnricherConfig{}
	mi := &file_data_object_enricher_data_object_enricher_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataObjectEnricherConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataObjectEnricherConfig) ProtoMessage() {}

func (x *DataObjectEnricherConfig) ProtoReflect() protoreflect.Message {
	mi := &file_data_object_enricher_data_object_enricher_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataObjectEnricherConfig.ProtoReflect.Descriptor instead.
func (*DataObjectEnricherConfig) Descriptor() ([]byte, []int) {
	return file_data_object_enricher_data_object_enricher_proto_rawDescGZIP(), []int{0}
}

func (x *DataObjectEnricherConfig) GetConfigMap() *config.ConfigMap {
	if x != nil {
		return x.ConfigMap
	}
	return nil
}

func (x *DataObjectEnricherConfig) GetInputFile() string {
	if x != nil {
		return x.InputFile
	}
	return ""
}

func (x *DataObjectEnricherConfig) GetOutputFile() string {
	if x != nil {
		return x.OutputFile
	}
	return ""
}

// DataObjectEnricherResult represents the result from the DataObjectEnricher process.
// A potential error is also modeled in here so specific errors remain intact when passed over RPC.
type DataObjectEnricherResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enriched      int32                  `protobuf:"varint,1,opt,name=enriched,proto3" json:"enriched,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataObjectEnricherResult) Reset() {
	*x = DataObjectEnricherResult{}
	mi := &file_data_object_enricher_data_object_enricher_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataObjectEnricherResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataObjectEnricherResult) ProtoMessage() {}

func (x *DataObjectEnricherResult) ProtoReflect() protoreflect.Message {
	mi := &file_data_object_enricher_data_object_enricher_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataObjectEnricherResult.ProtoReflect.Descriptor instead.
func (*DataObjectEnricherResult) Descriptor() ([]byte, []int) {
	return file_data_object_enricher_data_object_enricher_proto_rawDescGZIP(), []int{1}
}

func (x *DataObjectEnricherResult) GetEnriched() int32 {
	if x != nil {
		return x.Enriched
	}
	return 0
}

var File_data_object_enricher_data_object_enricher_proto protoreflect.FileDescriptor

const file_data_object_enricher_data_object_enricher_proto_rawDesc = "" +
	"\n" +
	"/data_object_enricher/data_object_enricher.proto\x12\x14data_object_enricher\x1a\x1bgoogle/protobuf/empty.proto\x1a\x18util/config/config.proto\x1a\x1autil/version/version.proto\"\x91\x01\n" +
	"\x18DataObjectEnricherConfig\x125\n" +
	"\n" +
	"config_map\x18\x01 \x01(\v2\x16.util.config.ConfigMapR\tconfigMap\x12\x1d\n" +
	"\n" +
	"input_file\x18\x02 \x01(\tR\tinputFile\x12\x1f\n" +
	"\voutput_file\x18\x03 \x01(\tR\n" +
	"outputFile\"6\n" +
	"\x18DataObjectEnricherResult\x12\x1a\n" +
	"\benriched\x18\x01 \x01(\x05R\benriched2\xd9\x01\n" +
	"\x19DataObjectEnricherService\x12R\n" +
	"\x15CliVersionInformation\x12\x16.google.protobuf.Empty\x1a!.util.version.CliBuildInformation\x12h\n" +
	"\x06Enrich\x12..data_object_enricher.DataObjectEnricherConfig\x1a..data_object_enricher.DataObjectEnricherResultB\xce\x01\n" +
	"\x18com.data_object_enricherB\x17DataObjectEnricherProtoP\x01Z1github.com/raito-io/cli/base/data_object_enricher\xa2\x02\x03DXX\xaa\x02\x12DataObjectEnricher\xca\x02\x12DataObjectEnricher\xe2\x02\x1eDataObjectEnricher\\GPBMetadata\xea\x02\x12DataObjectEnricherb\x06proto3"

var (
	file_data_object_enricher_data_object_enricher_proto_rawDescOnce sync.Once
	file_data_object_enricher_data_object_enricher_proto_rawDescData []byte
)

func file_data_object_enricher_data_object_enricher_proto_rawDescGZIP() []byte {
	file_data_object_enricher_data_object_enricher_proto_rawDescOnce.Do(func() {
		file_data_object_enricher_data_object_enricher_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_data_object_enricher_data_object_enricher_proto_rawDesc), len(file_data_object_enricher_data_object_enricher_proto_rawDesc)))
	})
	return file_data_object_enricher_data_object_enricher_proto_rawDescData
}

var file_data_object_enricher_data_object_enricher_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_data_object_enricher_data_object_enricher_proto_goTypes = []any{
	(*DataObjectEnricherConfig)(nil),    // 0: data_object_enricher.DataObjectEnricherConfig
	(*DataObjectEnricherResult)(nil),    // 1: data_object_enricher.DataObjectEnricherResult
	(*config.ConfigMap)(nil),            // 2: util.config.ConfigMap
	(*emptypb.Empty)(nil),               // 3: google.protobuf.Empty
	(*version.CliBuildInformation)(nil), // 4: util.version.CliBuildInformation
}
var file_data_object_enricher_data_object_enricher_proto_depIdxs = []int32{
	2, // 0: data_object_enricher.DataObjectEnricherConfig.config_map:type_name -> util.config.ConfigMap
	3, // 1: data_object_enricher.DataObjectEnricherService.CliVersionInformation:input_type -> google.protobuf.Empty
	0, // 2: data_object_enricher.DataObjectEnricherService.Enrich:input_type -> data_object_enricher.DataObjectEnricherConfig
	4, // 3: data_object_enricher.DataObjectEnricherService.CliVersionInformation:output_type -> util.version.CliBuildInformation
	1, // 4: data_object_enricher.DataObjectEnricherService.Enrich:output_type -> data_object_enricher.DataObjectEnricherResult
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_data_object_enricher_data_object_enricher_proto_init() }
func file_data_object_enricher_data_object_enricher_proto_init() {
	if File_data_object_enricher_data_object_enricher_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_object_enricher_data_object_enricher_proto_rawDesc), len(file_data_object_enricher_data_object_enricher_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_data_object_enricher_data_object_enricher_proto_goTypes,
		DependencyIndexes: file_data_object_enricher_data_object_enricher_proto_depIdxs,
		MessageInfos:      file_data_object_enricher_data_object_enricher_proto_msgTypes,
	}.Build()
	File_data_object_enricher_data_object_enricher_proto = out.File
	file_data_object_enricher_data_object_enricher_proto_goTypes = nil
	file_data_object_enricher_data_object_enricher_proto_depIdxs = nil
}
