// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package data_object_enricher

import (
	context "context"
	version "github.com/raito-io/cli/base/util/version"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DataObjectEnricherServiceClient is the client API for DataObjectEnricherService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataObjectEnricherServiceClient interface {
	CliVersionInformation(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*version.CliBuildInformation, error)
	Enrich(ctx context.Context, in *DataObjectEnricherConfig, opts ...grpc.CallOption) (*DataObjectEnricherResult, error)
}

type dataObjectEnricherServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataObjectEnricherServiceClient(cc grpc.ClientConnInterface) DataObjectEnricherServiceClient {
	return &dataObjectEnricherServiceClient{cc}
}

func (c *dataObjectEnricherServiceClient) CliVersionInformation(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*version.CliBuildInformation, error) {
	out := new(version.CliBuildInformation)
	err := c.cc.Invoke(ctx, "/data_object_enricher.DataObjectEnricherService/CliVersionInformation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataObjectEnricherServiceClient) Enrich(ctx context.Context, in *DataObjectEnricherConfig, opts ...grpc.CallOption) (*DataObjectEnricherResult, error) {
	out := new(DataObjectEnricherResult)
	err := c.cc.Invoke(ctx, "/data_object_enricher.DataObjectEnricherService/Enrich", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataObjectEnricherServiceServer is the server API for DataObjectEnricherService service.
// All implementations must embed UnimplementedDataObjectEnricherServiceServer
// for forward compatibility
type DataObjectEnricherServiceServer interface {
	CliVersionInformation(context.Context, *emptypb.Empty) (*version.CliBuildInformation, error)
	Enrich(context.Context, *DataObjectEnricherConfig) (*DataObjectEnricherResult, error)
	mustEmbedUnimplementedDataObjectEnricherServiceServer()
}

// UnimplementedDataObjectEnricherServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDataObjectEnricherServiceServer struct {
}

func (UnimplementedDataObjectEnricherServiceServer) CliVersionInformation(context.Context, *emptypb.Empty) (*version.CliBuildInformation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CliVersionInformation not implemented")
}
func (UnimplementedDataObjectEnricherServiceServer) Enrich(context.Context, *DataObjectEnricherConfig) (*DataObjectEnricherResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Enrich not implemented")
}
func (UnimplementedDataObjectEnricherServiceServer) mustEmbedUnimplementedDataObjectEnricherServiceServer() {
}

// UnsafeDataObjectEnricherServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataObjectEnricherServiceServer will
// result in compilation errors.
type UnsafeDataObjectEnricherServiceServer interface {
	mustEmbedUnimplementedDataObjectEnricherServiceServer()
}

func RegisterDataObjectEnricherServiceServer(s grpc.ServiceRegistrar, srv DataObjectEnricherServiceServer) {
	s.RegisterService(&DataObjectEnricherService_ServiceDesc, srv)
}

func _DataObjectEnricherService_CliVersionInformation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataObjectEnricherServiceServer).CliVersionInformation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/data_object_enricher.DataObjectEnricherService/CliVersionInformation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataObjectEnricherServiceServer).CliVersionInformation(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataObjectEnricherService_Enrich_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataObjectEnricherConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataObjectEnricherServiceServer).Enrich(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/data_object_enricher.DataObjectEnricherService/Enrich",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataObjectEnricherServiceServer).Enrich(ctx, req.(*DataObjectEnricherConfig))
	}
	return interceptor(ctx, in, info, handler)
}

// DataObjectEnricherService_ServiceDesc is the grpc.ServiceDesc for DataObjectEnricherService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataObjectEnricherService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "data_object_enricher.DataObjectEnricherService",
	HandlerType: (*DataObjectEnricherServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CliVersionInformation",
			Handler:    _DataObjectEnricherService_CliVersionInformation_Handler,
		},
		{
			MethodName: "Enrich",
			Handler:    _DataObjectEnricherService_Enrich_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "data_object_enricher/data_object_enricher.proto",
}
