// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: util/config/config.proto

package config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parameters    map[string]string      `protobuf:"bytes,1,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigMap) Reset() {
	*x = ConfigMap{}
	mi := &file_util_config_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigMap) ProtoMessage() {}

func (x *ConfigMap) ProtoReflect() protoreflect.Message {
	mi := &file_util_config_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigMap.ProtoReflect.Descriptor instead.
func (*ConfigMap) Descriptor() ([]byte, []int) {
	return file_util_config_config_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigMap) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

var File_util_config_config_proto protoreflect.FileDescriptor

const file_util_config_config_proto_rawDesc = "" +
	"\n" +
	"\x18util/config/config.proto\x12\vutil.config\"\x92\x01\n" +
	"\tConfigMap\x12F\n" +
	"\n" +
	"parameters\x18\x01 \x03(\v2&.util.config.ConfigMap.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x95\x01\n" +
	"\x0fcom.util.configB\vConfigProtoP\x01Z(github.com/raito-io/cli/base/util/config\xa2\x02\x03UCX\xaa\x02\vUtil.Config\xca\x02\vUtil\\Config\xe2\x02\x17Util\\Config\\GPBMetadata\xea\x02\fUtil::Configb\x06proto3"

var (
	file_util_config_config_proto_rawDescOnce sync.Once
	file_util_config_config_proto_rawDescData []byte
)

func file_util_config_config_proto_rawDescGZIP() []byte {
	file_util_config_config_proto_rawDescOnce.Do(func() {
		file_util_config_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_util_config_config_proto_rawDesc), len(file_util_config_config_proto_rawDesc)))
	})
	return file_util_config_config_proto_rawDescData
}

var file_util_config_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_util_config_config_proto_goTypes = []any{
	(*ConfigMap)(nil), // 0: util.config.ConfigMap
	nil,               // 1: util.config.ConfigMap.ParametersEntry
}
var file_util_config_config_proto_depIdxs = []int32{
	1, // 0: util.config.ConfigMap.parameters:type_name -> util.config.ConfigMap.ParametersEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_util_config_config_proto_init() }
func file_util_config_config_proto_init() {
	if File_util_config_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_util_config_config_proto_rawDesc), len(file_util_config_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_util_config_config_proto_goTypes,
		DependencyIndexes: file_util_config_config_proto_depIdxs,
		MessageInfos:      file_util_config_config_proto_msgTypes,
	}.Build()
	File_util_config_config_proto = out.File
	file_util_config_config_proto_goTypes = nil
	file_util_config_config_proto_depIdxs = nil
}
