// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: data_usage/data_usage.proto

package data_usage

import (
	config "github.com/raito-io/cli/base/util/config"
	error1 "github.com/raito-io/cli/base/util/error"
	version "github.com/raito-io/cli/base/util/version"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DataUsageSyncConfig represents the configuration that is passed from the CLI to the DataUsageSyncer plugin interface.
// It contains all the necessary configuration parameters for the plugin to function.
type DataUsageSyncConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConfigMap       *config.ConfigMap      `protobuf:"bytes,1,opt,name=config_map,json=configMap,proto3" json:"config_map,omitempty"`
	TargetFile      string                 `protobuf:"bytes,2,opt,name=target_file,json=targetFile,proto3" json:"target_file,omitempty"`
	MaxBytesPerFile uint64                 `protobuf:"varint,3,opt,name=max_bytes_per_file,json=maxBytesPerFile,proto3" json:"max_bytes_per_file,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DataUsageSyncConfig) Reset() {
	*x = DataUsageSyncConfig{}
	mi := &file_data_usage_data_usage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataUsageSyncConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataUsageSyncConfig) ProtoMessage() {}

func (x *DataUsageSyncConfig) ProtoReflect() protoreflect.Message {
	mi := &file_data_usage_data_usage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataUsageSyncConfig.ProtoReflect.Descriptor instead.
func (*DataUsageSyncConfig) Descriptor() ([]byte, []int) {
	return file_data_usage_data_usage_proto_rawDescGZIP(), []int{0}
}

func (x *DataUsageSyncConfig) GetConfigMap() *config.ConfigMap {
	if x != nil {
		return x.ConfigMap
	}
	return nil
}

func (x *DataUsageSyncConfig) GetTargetFile() string {
	if x != nil {
		return x.TargetFile
	}
	return ""
}

func (x *DataUsageSyncConfig) GetMaxBytesPerFile() uint64 {
	if x != nil {
		return x.MaxBytesPerFile
	}
	return 0
}

// DataUsageSyncResult represents the result from the data usage sync process.
// A potential error is also modeled in here so specific errors remain intact when passed over RPC.
type DataUsageSyncResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deprecated: Marked as deprecated in data_usage/data_usage.proto.
	Error         *error1.ErrorResult `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Statements    int32               `protobuf:"varint,2,opt,name=statements,proto3" json:"statements,omitempty"`
	TargetFiles   []string            `protobuf:"bytes,3,rep,name=target_files,json=targetFiles,proto3" json:"target_files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataUsageSyncResult) Reset() {
	*x = DataUsageSyncResult{}
	mi := &file_data_usage_data_usage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataUsageSyncResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataUsageSyncResult) ProtoMessage() {}

func (x *DataUsageSyncResult) ProtoReflect() protoreflect.Message {
	mi := &file_data_usage_data_usage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataUsageSyncResult.ProtoReflect.Descriptor instead.
func (*DataUsageSyncResult) Descriptor() ([]byte, []int) {
	return file_data_usage_data_usage_proto_rawDescGZIP(), []int{1}
}

// Deprecated: Marked as deprecated in data_usage/data_usage.proto.
func (x *DataUsageSyncResult) GetError() *error1.ErrorResult {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *DataUsageSyncResult) GetStatements() int32 {
	if x != nil {
		return x.Statements
	}
	return 0
}

func (x *DataUsageSyncResult) GetTargetFiles() []string {
	if x != nil {
		return x.TargetFiles
	}
	return nil
}

var File_data_usage_data_usage_proto protoreflect.FileDescriptor

const file_data_usage_data_usage_proto_rawDesc = "" +
	"\n" +
	"\x1bdata_usage/data_usage.proto\x12\n" +
	"data_usage\x1a\x1bgoogle/protobuf/empty.proto\x1a\x18util/config/config.proto\x1a\x16util/error/error.proto\x1a\x1autil/version/version.proto\"\x9a\x01\n" +
	"\x13DataUsageSyncConfig\x125\n" +
	"\n" +
	"config_map\x18\x01 \x01(\v2\x16.util.config.ConfigMapR\tconfigMap\x12\x1f\n" +
	"\vtarget_file\x18\x02 \x01(\tR\n" +
	"targetFile\x12+\n" +
	"\x12max_bytes_per_file\x18\x03 \x01(\x04R\x0fmaxBytesPerFile\"\x8b\x01\n" +
	"\x13DataUsageSyncResult\x121\n" +
	"\x05error\x18\x01 \x01(\v2\x17.util.error.ErrorResultB\x02\x18\x01R\x05error\x12\x1e\n" +
	"\n" +
	"statements\x18\x02 \x01(\x05R\n" +
	"statements\x12!\n" +
	"\ftarget_files\x18\x03 \x03(\tR\vtargetFiles2\xbd\x01\n" +
	"\x14DataUsageSyncService\x12R\n" +
	"\x15CliVersionInformation\x12\x16.google.protobuf.Empty\x1a!.util.version.CliBuildInformation\x12Q\n" +
	"\rSyncDataUsage\x12\x1f.data_usage.DataUsageSyncConfig\x1a\x1f.data_usage.DataUsageSyncResultB\x8d\x01\n" +
	"\x0ecom.data_usageB\x0eDataUsageProtoP\x01Z'github.com/raito-io/cli/base/data_usage\xa2\x02\x03DXX\xaa\x02\tDataUsage\xca\x02\tDataUsage\xe2\x02\x15DataUsage\\GPBMetadata\xea\x02\tDataUsageb\x06proto3"

var (
	file_data_usage_data_usage_proto_rawDescOnce sync.Once
	file_data_usage_data_usage_proto_rawDescData []byte
)

func file_data_usage_data_usage_proto_rawDescGZIP() []byte {
	file_data_usage_data_usage_proto_rawDescOnce.Do(func() {
		file_data_usage_data_usage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_data_usage_data_usage_proto_rawDesc), len(file_data_usage_data_usage_proto_rawDesc)))
	})
	return file_data_usage_data_usage_proto_rawDescData
}

var file_data_usage_data_usage_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_data_usage_data_usage_proto_goTypes = []any{
	(*DataUsageSyncConfig)(nil),         // 0: data_usage.DataUsageSyncConfig
	(*DataUsageSyncResult)(nil),         // 1: data_usage.DataUsageSyncResult
	(*config.ConfigMap)(nil),            // 2: util.config.ConfigMap
	(*error1.ErrorResult)(nil),          // 3: util.error.ErrorResult
	(*emptypb.Empty)(nil),               // 4: google.protobuf.Empty
	(*version.CliBuildInformation)(nil), // 5: util.version.CliBuildInformation
}
var file_data_usage_data_usage_proto_depIdxs = []int32{
	2, // 0: data_usage.DataUsageSyncConfig.config_map:type_name -> util.config.ConfigMap
	3, // 1: data_usage.DataUsageSyncResult.error:type_name -> util.error.ErrorResult
	4, // 2: data_usage.DataUsageSyncService.CliVersionInformation:input_type -> google.protobuf.Empty
	0, // 3: data_usage.DataUsageSyncService.SyncDataUsage:input_type -> data_usage.DataUsageSyncConfig
	5, // 4: data_usage.DataUsageSyncService.CliVersionInformation:output_type -> util.version.CliBuildInformation
	1, // 5: data_usage.DataUsageSyncService.SyncDataUsage:output_type -> data_usage.DataUsageSyncResult
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_data_usage_data_usage_proto_init() }
func file_data_usage_data_usage_proto_init() {
	if File_data_usage_data_usage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_usage_data_usage_proto_rawDesc), len(file_data_usage_data_usage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_data_usage_data_usage_proto_goTypes,
		DependencyIndexes: file_data_usage_data_usage_proto_depIdxs,
		MessageInfos:      file_data_usage_data_usage_proto_msgTypes,
	}.Build()
	File_data_usage_data_usage_proto = out.File
	file_data_usage_data_usage_proto_goTypes = nil
	file_data_usage_data_usage_proto_depIdxs = nil
}
