// Code generated by mockery v2.14.0. DO NOT EDIT.

package wrappers

import (
	context "context"

	config "github.com/raito-io/cli/base/util/config"

	mock "github.com/stretchr/testify/mock"

	sync_to_target "github.com/raito-io/cli/base/access_provider/sync_to_target"
)

// MockAccessProviderSyncer is an autogenerated mock type for the AccessProviderSyncer type
type MockAccessProviderSyncer struct {
	mock.Mock
}

type MockAccessProviderSyncer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccessProviderSyncer) EXPECT() *MockAccessProviderSyncer_Expecter {
	return &MockAccessProviderSyncer_Expecter{mock: &_m.Mock}
}

// SyncAccessAsCodeToTarget provides a mock function with given fields: ctx, accesses, configMap
func (_m *MockAccessProviderSyncer) SyncAccessAsCodeToTarget(ctx context.Context, accesses map[string]sync_to_target.EnrichedAccess, configMap *config.ConfigMap) error {
	ret := _m.Called(ctx, accesses, configMap)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, map[string]sync_to_target.EnrichedAccess, *config.ConfigMap) error); ok {
		r0 = rf(ctx, accesses, configMap)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccessProviderSyncer_SyncAccessAsCodeToTarget_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncAccessAsCodeToTarget'
type MockAccessProviderSyncer_SyncAccessAsCodeToTarget_Call struct {
	*mock.Call
}

// SyncAccessAsCodeToTarget is a helper method to define mock.On call
//   - ctx context.Context
//   - accesses map[string]sync_to_target.EnrichedAccess
//   - configMap *config.ConfigMap
func (_e *MockAccessProviderSyncer_Expecter) SyncAccessAsCodeToTarget(ctx interface{}, accesses interface{}, configMap interface{}) *MockAccessProviderSyncer_SyncAccessAsCodeToTarget_Call {
	return &MockAccessProviderSyncer_SyncAccessAsCodeToTarget_Call{Call: _e.mock.On("SyncAccessAsCodeToTarget", ctx, accesses, configMap)}
}

func (_c *MockAccessProviderSyncer_SyncAccessAsCodeToTarget_Call) Run(run func(ctx context.Context, accesses map[string]sync_to_target.EnrichedAccess, configMap *config.ConfigMap)) *MockAccessProviderSyncer_SyncAccessAsCodeToTarget_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(map[string]sync_to_target.EnrichedAccess), args[2].(*config.ConfigMap))
	})
	return _c
}

func (_c *MockAccessProviderSyncer_SyncAccessAsCodeToTarget_Call) Return(_a0 error) *MockAccessProviderSyncer_SyncAccessAsCodeToTarget_Call {
	_c.Call.Return(_a0)
	return _c
}

// SyncAccessProviderFromTarget provides a mock function with given fields: ctx, accessProviderHandler, configMap
func (_m *MockAccessProviderSyncer) SyncAccessProviderFromTarget(ctx context.Context, accessProviderHandler AccessProviderHandler, configMap *config.ConfigMap) error {
	ret := _m.Called(ctx, accessProviderHandler, configMap)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, AccessProviderHandler, *config.ConfigMap) error); ok {
		r0 = rf(ctx, accessProviderHandler, configMap)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccessProviderSyncer_SyncAccessProviderFromTarget_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncAccessProviderFromTarget'
type MockAccessProviderSyncer_SyncAccessProviderFromTarget_Call struct {
	*mock.Call
}

// SyncAccessProviderFromTarget is a helper method to define mock.On call
//   - ctx context.Context
//   - accessProviderHandler AccessProviderHandler
//   - configMap *config.ConfigMap
func (_e *MockAccessProviderSyncer_Expecter) SyncAccessProviderFromTarget(ctx interface{}, accessProviderHandler interface{}, configMap interface{}) *MockAccessProviderSyncer_SyncAccessProviderFromTarget_Call {
	return &MockAccessProviderSyncer_SyncAccessProviderFromTarget_Call{Call: _e.mock.On("SyncAccessProviderFromTarget", ctx, accessProviderHandler, configMap)}
}

func (_c *MockAccessProviderSyncer_SyncAccessProviderFromTarget_Call) Run(run func(ctx context.Context, accessProviderHandler AccessProviderHandler, configMap *config.ConfigMap)) *MockAccessProviderSyncer_SyncAccessProviderFromTarget_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(AccessProviderHandler), args[2].(*config.ConfigMap))
	})
	return _c
}

func (_c *MockAccessProviderSyncer_SyncAccessProviderFromTarget_Call) Return(_a0 error) *MockAccessProviderSyncer_SyncAccessProviderFromTarget_Call {
	_c.Call.Return(_a0)
	return _c
}

// SyncAccessProviderToTarget provides a mock function with given fields: ctx, rolesToRemove, accesses, feedbackHandler, configMap
func (_m *MockAccessProviderSyncer) SyncAccessProviderToTarget(ctx context.Context, rolesToRemove []string, accesses map[string]sync_to_target.EnrichedAccess, feedbackHandler AccessProviderFeedbackHandler, configMap *config.ConfigMap) error {
	ret := _m.Called(ctx, rolesToRemove, accesses, feedbackHandler, configMap)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, map[string]sync_to_target.EnrichedAccess, AccessProviderFeedbackHandler, *config.ConfigMap) error); ok {
		r0 = rf(ctx, rolesToRemove, accesses, feedbackHandler, configMap)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccessProviderSyncer_SyncAccessProviderToTarget_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncAccessProviderToTarget'
type MockAccessProviderSyncer_SyncAccessProviderToTarget_Call struct {
	*mock.Call
}

// SyncAccessProviderToTarget is a helper method to define mock.On call
//   - ctx context.Context
//   - rolesToRemove []string
//   - accesses map[string]sync_to_target.EnrichedAccess
//   - feedbackHandler AccessProviderFeedbackHandler
//   - configMap *config.ConfigMap
func (_e *MockAccessProviderSyncer_Expecter) SyncAccessProviderToTarget(ctx interface{}, rolesToRemove interface{}, accesses interface{}, feedbackHandler interface{}, configMap interface{}) *MockAccessProviderSyncer_SyncAccessProviderToTarget_Call {
	return &MockAccessProviderSyncer_SyncAccessProviderToTarget_Call{Call: _e.mock.On("SyncAccessProviderToTarget", ctx, rolesToRemove, accesses, feedbackHandler, configMap)}
}

func (_c *MockAccessProviderSyncer_SyncAccessProviderToTarget_Call) Run(run func(ctx context.Context, rolesToRemove []string, accesses map[string]sync_to_target.EnrichedAccess, feedbackHandler AccessProviderFeedbackHandler, configMap *config.ConfigMap)) *MockAccessProviderSyncer_SyncAccessProviderToTarget_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string), args[2].(map[string]sync_to_target.EnrichedAccess), args[3].(AccessProviderFeedbackHandler), args[4].(*config.ConfigMap))
	})
	return _c
}

func (_c *MockAccessProviderSyncer_SyncAccessProviderToTarget_Call) Return(_a0 error) *MockAccessProviderSyncer_SyncAccessProviderToTarget_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewMockAccessProviderSyncer interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockAccessProviderSyncer creates a new instance of MockAccessProviderSyncer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockAccessProviderSyncer(t mockConstructorTestingTNewMockAccessProviderSyncer) *MockAccessProviderSyncer {
	mock := &MockAccessProviderSyncer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
