// Code generated by mockery v2.14.0. DO NOT EDIT.

package wrappers

import (
	context "context"

	config "github.com/raito-io/cli/base/util/config"

	data_source "github.com/raito-io/cli/base/data_source"

	mock "github.com/stretchr/testify/mock"
)

// MockDataSourceSyncer is an autogenerated mock type for the DataSourceSyncer type
type MockDataSourceSyncer struct {
	mock.Mock
}

type MockDataSourceSyncer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDataSourceSyncer) EXPECT() *MockDataSourceSyncer_Expecter {
	return &MockDataSourceSyncer_Expecter{mock: &_m.Mock}
}

// GetDataSourceMetaData provides a mock function with given fields:
func (_m *MockDataSourceSyncer) GetDataSourceMetaData() data_source.MetaData {
	ret := _m.Called()

	var r0 data_source.MetaData
	if rf, ok := ret.Get(0).(func() data_source.MetaData); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(data_source.MetaData)
	}

	return r0
}

// MockDataSourceSyncer_GetDataSourceMetaData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDataSourceMetaData'
type MockDataSourceSyncer_GetDataSourceMetaData_Call struct {
	*mock.Call
}

// GetDataSourceMetaData is a helper method to define mock.On call
func (_e *MockDataSourceSyncer_Expecter) GetDataSourceMetaData() *MockDataSourceSyncer_GetDataSourceMetaData_Call {
	return &MockDataSourceSyncer_GetDataSourceMetaData_Call{Call: _e.mock.On("GetDataSourceMetaData")}
}

func (_c *MockDataSourceSyncer_GetDataSourceMetaData_Call) Run(run func()) *MockDataSourceSyncer_GetDataSourceMetaData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDataSourceSyncer_GetDataSourceMetaData_Call) Return(_a0 data_source.MetaData) *MockDataSourceSyncer_GetDataSourceMetaData_Call {
	_c.Call.Return(_a0)
	return _c
}

// SyncDataSource provides a mock function with given fields: ctx, dataSourceHandler, configParams
func (_m *MockDataSourceSyncer) SyncDataSource(ctx context.Context, dataSourceHandler DataSourceObjectHandler, configParams *config.ConfigMap) error {
	ret := _m.Called(ctx, dataSourceHandler, configParams)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, DataSourceObjectHandler, *config.ConfigMap) error); ok {
		r0 = rf(ctx, dataSourceHandler, configParams)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDataSourceSyncer_SyncDataSource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncDataSource'
type MockDataSourceSyncer_SyncDataSource_Call struct {
	*mock.Call
}

// SyncDataSource is a helper method to define mock.On call
//   - ctx context.Context
//   - dataSourceHandler DataSourceObjectHandler
//   - configParams *config.ConfigMap
func (_e *MockDataSourceSyncer_Expecter) SyncDataSource(ctx interface{}, dataSourceHandler interface{}, configParams interface{}) *MockDataSourceSyncer_SyncDataSource_Call {
	return &MockDataSourceSyncer_SyncDataSource_Call{Call: _e.mock.On("SyncDataSource", ctx, dataSourceHandler, configParams)}
}

func (_c *MockDataSourceSyncer_SyncDataSource_Call) Run(run func(ctx context.Context, dataSourceHandler DataSourceObjectHandler, configParams *config.ConfigMap)) *MockDataSourceSyncer_SyncDataSource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(DataSourceObjectHandler), args[2].(*config.ConfigMap))
	})
	return _c
}

func (_c *MockDataSourceSyncer_SyncDataSource_Call) Return(_a0 error) *MockDataSourceSyncer_SyncDataSource_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewMockDataSourceSyncer interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockDataSourceSyncer creates a new instance of MockDataSourceSyncer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockDataSourceSyncer(t mockConstructorTestingTNewMockDataSourceSyncer) *MockDataSourceSyncer {
	mock := &MockDataSourceSyncer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
