// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: tag/tag.proto

package tag

import (
	config "github.com/raito-io/cli/base/util/config"
	version "github.com/raito-io/cli/base/util/version"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TagSyncConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConfigMap       *config.ConfigMap      `protobuf:"bytes,1,opt,name=config_map,json=configMap,proto3" json:"config_map,omitempty"`
	TargetFile      string                 `protobuf:"bytes,2,opt,name=target_file,json=targetFile,proto3" json:"target_file,omitempty"`
	DataSourceId    string                 `protobuf:"bytes,3,opt,name=data_source_id,json=dataSourceId,proto3" json:"data_source_id,omitempty"`
	IdentityStoreId string                 `protobuf:"bytes,4,opt,name=identity_store_id,json=identityStoreId,proto3" json:"identity_store_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TagSyncConfig) Reset() {
	*x = TagSyncConfig{}
	mi := &file_tag_tag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagSyncConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagSyncConfig) ProtoMessage() {}

func (x *TagSyncConfig) ProtoReflect() protoreflect.Message {
	mi := &file_tag_tag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagSyncConfig.ProtoReflect.Descriptor instead.
func (*TagSyncConfig) Descriptor() ([]byte, []int) {
	return file_tag_tag_proto_rawDescGZIP(), []int{0}
}

func (x *TagSyncConfig) GetConfigMap() *config.ConfigMap {
	if x != nil {
		return x.ConfigMap
	}
	return nil
}

func (x *TagSyncConfig) GetTargetFile() string {
	if x != nil {
		return x.TargetFile
	}
	return ""
}

func (x *TagSyncConfig) GetDataSourceId() string {
	if x != nil {
		return x.DataSourceId
	}
	return ""
}

func (x *TagSyncConfig) GetIdentityStoreId() string {
	if x != nil {
		return x.IdentityStoreId
	}
	return ""
}

type TagSyncResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Tags            int32                  `protobuf:"varint,1,opt,name=tags,proto3" json:"tags,omitempty"`
	TagSourcesScope []string               `protobuf:"bytes,2,rep,name=tag_sources_scope,json=tagSourcesScope,proto3" json:"tag_sources_scope,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TagSyncResult) Reset() {
	*x = TagSyncResult{}
	mi := &file_tag_tag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagSyncResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagSyncResult) ProtoMessage() {}

func (x *TagSyncResult) ProtoReflect() protoreflect.Message {
	mi := &file_tag_tag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagSyncResult.ProtoReflect.Descriptor instead.
func (*TagSyncResult) Descriptor() ([]byte, []int) {
	return file_tag_tag_proto_rawDescGZIP(), []int{1}
}

func (x *TagSyncResult) GetTags() int32 {
	if x != nil {
		return x.Tags
	}
	return 0
}

func (x *TagSyncResult) GetTagSourcesScope() []string {
	if x != nil {
		return x.TagSourcesScope
	}
	return nil
}

var File_tag_tag_proto protoreflect.FileDescriptor

const file_tag_tag_proto_rawDesc = "" +
	"\n" +
	"\rtag/tag.proto\x12\x03tag\x1a\x1bgoogle/protobuf/empty.proto\x1a\x18util/config/config.proto\x1a\x1autil/version/version.proto\"\xb9\x01\n" +
	"\rTagSyncConfig\x125\n" +
	"\n" +
	"config_map\x18\x01 \x01(\v2\x16.util.config.ConfigMapR\tconfigMap\x12\x1f\n" +
	"\vtarget_file\x18\x02 \x01(\tR\n" +
	"targetFile\x12$\n" +
	"\x0edata_source_id\x18\x03 \x01(\tR\fdataSourceId\x12*\n" +
	"\x11identity_store_id\x18\x04 \x01(\tR\x0fidentityStoreId\"O\n" +
	"\rTagSyncResult\x12\x12\n" +
	"\x04tags\x18\x01 \x01(\x05R\x04tags\x12*\n" +
	"\x11tag_sources_scope\x18\x02 \x03(\tR\x0ftagSourcesScope2\x98\x01\n" +
	"\x0eTagSyncService\x12R\n" +
	"\x15CliVersionInformation\x12\x16.google.protobuf.Empty\x1a!.util.version.CliBuildInformation\x122\n" +
	"\bSyncTags\x12\x12.tag.TagSyncConfig\x1a\x12.tag.TagSyncResultBa\n" +
	"\acom.tagB\bTagProtoP\x01Z github.com/raito-io/cli/base/tag\xa2\x02\x03TXX\xaa\x02\x03Tag\xca\x02\x03Tag\xe2\x02\x0fTag\\GPBMetadata\xea\x02\x03Tagb\x06proto3"

var (
	file_tag_tag_proto_rawDescOnce sync.Once
	file_tag_tag_proto_rawDescData []byte
)

func file_tag_tag_proto_rawDescGZIP() []byte {
	file_tag_tag_proto_rawDescOnce.Do(func() {
		file_tag_tag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tag_tag_proto_rawDesc), len(file_tag_tag_proto_rawDesc)))
	})
	return file_tag_tag_proto_rawDescData
}

var file_tag_tag_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tag_tag_proto_goTypes = []any{
	(*TagSyncConfig)(nil),               // 0: tag.TagSyncConfig
	(*TagSyncResult)(nil),               // 1: tag.TagSyncResult
	(*config.ConfigMap)(nil),            // 2: util.config.ConfigMap
	(*emptypb.Empty)(nil),               // 3: google.protobuf.Empty
	(*version.CliBuildInformation)(nil), // 4: util.version.CliBuildInformation
}
var file_tag_tag_proto_depIdxs = []int32{
	2, // 0: tag.TagSyncConfig.config_map:type_name -> util.config.ConfigMap
	3, // 1: tag.TagSyncService.CliVersionInformation:input_type -> google.protobuf.Empty
	0, // 2: tag.TagSyncService.SyncTags:input_type -> tag.TagSyncConfig
	4, // 3: tag.TagSyncService.CliVersionInformation:output_type -> util.version.CliBuildInformation
	1, // 4: tag.TagSyncService.SyncTags:output_type -> tag.TagSyncResult
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tag_tag_proto_init() }
func file_tag_tag_proto_init() {
	if File_tag_tag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tag_tag_proto_rawDesc), len(file_tag_tag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tag_tag_proto_goTypes,
		DependencyIndexes: file_tag_tag_proto_depIdxs,
		MessageInfos:      file_tag_tag_proto_msgTypes,
	}.Build()
	File_tag_tag_proto = out.File
	file_tag_tag_proto_goTypes = nil
	file_tag_tag_proto_depIdxs = nil
}
