// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: util/error/error.proto

package error

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCode int32

const (
	ErrorCode_NO_ERROR                      ErrorCode = 0
	ErrorCode_UNKNOWN_ERROR                 ErrorCode = 1
	ErrorCode_BAD_INPUT_PARAMETER_ERROR     ErrorCode = 2
	ErrorCode_MISSING_INPUT_PARAMETER_ERROR ErrorCode = 3
	ErrorCode_SOURCE_CONNECTION_ERROR       ErrorCode = 4
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "NO_ERROR",
		1: "UNKNOWN_ERROR",
		2: "BAD_INPUT_PARAMETER_ERROR",
		3: "MISSING_INPUT_PARAMETER_ERROR",
		4: "SOURCE_CONNECTION_ERROR",
	}
	ErrorCode_value = map[string]int32{
		"NO_ERROR":                      0,
		"UNKNOWN_ERROR":                 1,
		"BAD_INPUT_PARAMETER_ERROR":     2,
		"MISSING_INPUT_PARAMETER_ERROR": 3,
		"SOURCE_CONNECTION_ERROR":       4,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_util_error_error_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_util_error_error_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_util_error_error_proto_rawDescGZIP(), []int{0}
}

type ErrorResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorMessage  string                 `protobuf:"bytes,1,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ErrorCode     ErrorCode              `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3,enum=util.error.ErrorCode" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResult) Reset() {
	*x = ErrorResult{}
	mi := &file_util_error_error_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResult) ProtoMessage() {}

func (x *ErrorResult) ProtoReflect() protoreflect.Message {
	mi := &file_util_error_error_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResult.ProtoReflect.Descriptor instead.
func (*ErrorResult) Descriptor() ([]byte, []int) {
	return file_util_error_error_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ErrorResult) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_NO_ERROR
}

var File_util_error_error_proto protoreflect.FileDescriptor

const file_util_error_error_proto_rawDesc = "" +
	"\n" +
	"\x16util/error/error.proto\x12\n" +
	"util.error\"h\n" +
	"\vErrorResult\x12#\n" +
	"\rerror_message\x18\x01 \x01(\tR\ferrorMessage\x124\n" +
	"\n" +
	"error_code\x18\x02 \x01(\x0e2\x15.util.error.ErrorCodeR\terrorCode*\x8b\x01\n" +
	"\tErrorCode\x12\f\n" +
	"\bNO_ERROR\x10\x00\x12\x11\n" +
	"\rUNKNOWN_ERROR\x10\x01\x12\x1d\n" +
	"\x19BAD_INPUT_PARAMETER_ERROR\x10\x02\x12!\n" +
	"\x1dMISSING_INPUT_PARAMETER_ERROR\x10\x03\x12\x1b\n" +
	"\x17SOURCE_CONNECTION_ERROR\x10\x04B\x90\x01\n" +
	"\x0ecom.util.errorB\n" +
	"ErrorProtoP\x01Z'github.com/raito-io/cli/base/util/error\xa2\x02\x03UEX\xaa\x02\n" +
	"Util.Error\xca\x02\vUtil\\Error_\xe2\x02\x17Util\\Error_\\GPBMetadata\xea\x02\vUtil::Errorb\x06proto3"

var (
	file_util_error_error_proto_rawDescOnce sync.Once
	file_util_error_error_proto_rawDescData []byte
)

func file_util_error_error_proto_rawDescGZIP() []byte {
	file_util_error_error_proto_rawDescOnce.Do(func() {
		file_util_error_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_util_error_error_proto_rawDesc), len(file_util_error_error_proto_rawDesc)))
	})
	return file_util_error_error_proto_rawDescData
}

var file_util_error_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_util_error_error_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_util_error_error_proto_goTypes = []any{
	(ErrorCode)(0),      // 0: util.error.ErrorCode
	(*ErrorResult)(nil), // 1: util.error.ErrorResult
}
var file_util_error_error_proto_depIdxs = []int32{
	0, // 0: util.error.ErrorResult.error_code:type_name -> util.error.ErrorCode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_util_error_error_proto_init() }
func file_util_error_error_proto_init() {
	if File_util_error_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_util_error_error_proto_rawDesc), len(file_util_error_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_util_error_error_proto_goTypes,
		DependencyIndexes: file_util_error_error_proto_depIdxs,
		EnumInfos:         file_util_error_error_proto_enumTypes,
		MessageInfos:      file_util_error_error_proto_msgTypes,
	}.Build()
	File_util_error_error_proto = out.File
	file_util_error_error_proto_goTypes = nil
	file_util_error_error_proto_depIdxs = nil
}
